services:
  - type: web
    name: todo-app
    env: node
    region: india
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: DATABASE_HOST
        value: todo-api
      - key: DATABASE_USER
        value: root
      - key: DATABASE_PASSWORD
        value: 1234
      - key: DATABASE_NAME
        value: todos
