services:
  - type: web
    name: todo-app
    env: node
    region: oregon  
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_HOST
        value: todo-api
      - key: DATABASE_USER
        value: root
      - key: DATABASE_PASSWORD
        value: 1234
      - key: DATABASE_NAME
        value: todos
